### ISSUE TITLE
Glassfish 4 deployment

### ISSUE THREAD

**Issue by rangalo** [imixs/imixs-workflow#182]
I couldn't deploy the sample jsf application on glassfish 4. 

Is is possible ?

When I re-package the engine jar als osgi bundle the ejbs are not recognized by glassfish 4. Is an osgi bundle available ?

**Comment by rsoika** [comment]
Hi,
yes Glassfish 4 is a little bit tricky.  The Payara server is better supported.

The following issues are important for GlassFish 4

1. In web.xml you need to change the jersey servlet class

```
 <servlet-name>ImixsRestService</servlet-name>
    <!-- <servlet-class>com.sun.jersey.spi.container.servlet.ServletContainer</servlet-class>  -->
    <servlet-class>org.glassfish.jersey.servlet.ServletContainer</servlet-class>

```

2. For the EJB problem, you need to add the additional property 'disable-nonportable-jndi-names' to the EJB container and set the value to 'true'. You can do this form the web console. This issue is a really unhappy setting which was introduced with GlassFish 2 (I think) and which is still there for backward compatibility.

3. CDI is another issue. There is a setting 'enable-implicit-cdi' which I think need to be set to 'false'. But for that I am not really sure. You can do this setting from the commandline tool when glassfish is running with the following command:

`./bin/asadmin set configs.config.server-config.cdi-service.enable-implicit-cdi=false`


Another important issue is that GlassFish 4.1.0 and the Payara implement different behavior in handling EJBs. 

I must admit that I gave up at the end (a little bit frustrated and annoyed).

Maybe you can help me to write a tutorial how to setup Glassfish (or the JSF-Sample Application which we can maybe manage via a maven profile) the right way? I would be happy for that help!

===
Ralph

**Comment by rangalo** [comment]
Hello Ralph,

Thanks for the quick reply. We actually have payara server. I will follow your suggestions and try to setup.  At the end I will share what I did step by step. Do I need to do something special for payara ? 

Best Regards,
Hardik

**Comment by rangalo** [comment]
Hi, 

Here some details about what I have done so far with Payara 4.1.

1. I have created an osgi bundle which includes imixs-workflow-engine and imixs-workflow-core as  dependencies in the bundle.

2. I have created a wrapper ejb with @Stateless which has workflow service injected. 

```
When I deploy the bundle toava.lang.IllegalStateException: com.sun.proxy.$Proxy336 cannot be cast to javax.annotation.security.DeclareRoles. Related annotation information: annotation [@javax.annotation.security.DeclareRoles(value=[org.imixs.ACCESSLEVEL.NOACCESS, org.imixs.ACCESSLEVEL.READERACCESS, org.imixs.ACCESSLEVEL.AUTHORACCESS, org.imixs.ACCESSLEVEL.EDITORACCESS, org.imixs.ACCESSLEVEL.MANAGERACCESS])] on annotated element [class org.imixs.workflow.jee.ejb.ReportService] of type [TYPE]
	at com.sun.enterprise.deployment.archivist.Archivist.readAnnotations(Archivist.java:518)
	at com.sun.enterprise.deployment.archivist.Archivist.readAnnotations(Archivist.java:446)
	at com.sun.enterprise.deployment.archivist.Archivist.readRestDeploymentDescriptors(Archivist.java:419)
	at com.sun.enterprise.deployment.archivist.Archivist.readDeploymentDescriptors(Archivist.java:396)
	at com.sun.enterprise.deployment.archivist.Archivist.open(Archivist.java:271)
```

**Comment by rsoika** [comment]
I am not very familiar with the deployment of osgi bundles in glassfish. 
The IllegalStateException, I think, indicates a missing role mapping. The caller of you WcfImixsService need to be assigned at least to one of the Imixs Security roles. 
Did you have added a glassfish-ejb-jar.xml file with the role mapping? You can see the corresponding glassfish-web.xml file with the required role mapping in the JSF-Sample application in the folder /WEB-INF

**Comment by rangalo** [comment]
Yes. I have the glassfish-ejjb-jar.xml file. 

I have meanwhile managed to deploy the jsf example version: 3.6.1 to payara. Is the Rest service already inside ? Can I use it directly what is the context path for the rest service ? 

Again thanks for the support. 

Best Regards,
Hardik

**Comment by rsoika** [comment]
yes the rest service is part of the jsf-example and mapped to /rest-service/*
for example:
http://localhost:8080/rest-service/model

should show uploaded models

**Comment by rangalo** [comment]
Hi Ralph,

Thanks for the support. 

The example is now running under payara (gf 4.1). 

What I had to change was just the web.xml as you already pointed out. For my first try I was using java 8 and some java EE 7  libraries in the osgi bundle so thee approach failed. 

Best Regards,
Hardik

**Comment by rsoika** [comment]
ok - thanks for the feedback. I have now also added different maven profiles for the jsf-sample application.
