### ISSUE TITLE
Migration document to upgrade imixs workflow from GFV2.1 to Payara version application server

### ISSUE THREAD

**Issue by pshareef** [imixs/imixs-workflow#274]
Imix workflow is running on Glassfish application server V2.1 with below jars.
		imixs-workflow-api-2.1.0.jar
        imixs-workflow-jee-2.1.0.jar
        imixs-workflow-jee-impl-2.1.0.jar
        imixs-workflow-rest-2.1.0.war
        imixs-workflow-xml-2.1.0.jar

There is a migration document available here to migrate from Imixs-Workflow version 3.x to version 4.x but it is not useful to migrate from Glassfish version 2.1 to payara.

Could you please provide migration document to upgrade the above jar files to latest version on Glassfish payara version from Glassfish V2.1.

**Comment by rsoika** [comment]
Hi,
there are two different issues you need to care about:

**BPMN 2.0**
Since version 3.3, BPMN 2.0 was introduced. For that reason you need to migrate your old .ixm Models into BPMN. The Imixs-Workflow-core project includes a Migration Tool located under:

`/src/test/java/org/imixs/workflow/bpmn/MigrateImixsModelToBPMN`

With this tool you can migrate a .ixm file into a .bpmn file.

**Database Schema**
The second issue is the redesign of the workflow engine, which includes a change of the database schema and a new package design.
To deploy the new jar files, you can simply change the dependencies to the new artefacts

- imixs-workflow-core
- imixs-workflow-engine
- imixs-workflow-faces
- imixs-workflow-jax-rs

See the [jsf-sample-application](https://github.com/imixs/imixs-jsf-example) as an example for your deployment. 

In version 3.x and also in the latest version 4. we introduced a new data model with provides a much better performance and more flexibility. But the migration guide - as you already found out - is only concerning the migration from version 3 to 4.  So in your case you need a special migration job.

The best solution would be to adapt the class

`org.imixs.workflow.engine.adminp.JobHandlerMigration3X.java `

which is included in the imixs-workflow-engine.jar V 4.
If you adapt this class to the version 2.x, it is possible to use the new Admin Client and start the migration as explained in the actual migration guide. The Job simply loads the Entity from the old schema and stores the data into the new schema. 
The deployment could be a little bit tricky because you need to deploy both JPA libraries - imixs-workflow-jee-impl-2.1.0.jar and imixs-workflow-engine-4.1.2.jar


===
Ralph

**Comment by pshareef** [comment]
In the same time, would it be possible to have the IMIXS framework version 2 working on Glassfish Payara?

**Comment by rsoika** [comment]
What is the background of your project you are working on?

**Comment by pshareef** [comment]
We have two systems that are using the IMIXS v2 framework and are deployed on a GF2 environment. At this moment, my company decided to remove the GF2 from the enterprise and replace it with GF4. At this moment we are investigating the feasibility of each option and try to see what's the cheaper way to proceed further.

**Comment by pshareef** [comment]
Thank you very much and we are trying to migrate Imixs v2 on GF4 version. Will provide you the results.
