### ISSUE TITLE
Can't deploy imixs-jsf-example-4.0.4 on GlassFish server 4.1.2

### ISSUE THREAD

**Issue by chrisw14** [imixs/imixs-workflow#276]
Hi,
I downloaded the sample application from https://github.com/imixs/imixs-jsf-example/releases as war file and tried to deploy it on the GlassFish server 4.1.2 by following the instructions of http://www.imixs.org/doc/deployment/glassfish.html
If I want to import the war file, I got the following error:

> An error has occurred Error occurred during deployment: Exception while deploying the app [imixs-jsf-example-4.0.4] : Class org.imixs.application.jee.example.DemoPlugin has unsupported major or minor version numbers, which are greater than those found in the Java Runtime Environment version 1.7.0_17. Please see server.log for more details. 

How can I fix that?

Thanks, 
Chris

**Comment by rsoika** [comment]
Hi,
which Java Version you are running on Glassfish? 

===
Ralph

**Comment by chrisw14** [comment]
Hi,

it’s 1.7.0_17.

Thank you.

Chris

**Comment by rsoika** [comment]
Ok, I think the reason is, that we force JDK 1.8 for compiling the project.
See the pom.xml file of the sample application.
Can you try to checkout the sources and change the maven-compiler version as followed:

```
<plugin>
	<artifactId>maven-compiler-plugin</artifactId>
	<version>2.3.2</version>
	<configuration>
		<source>1.7</source>
		<target>1.7</target>
	</configuration>
</plugin>
```

Maybe this solve the issue.
But on the other hand the imixs-workflow project is also compiled with 1.8. So normally I would expect that after changing the jdk version for the sample application, glassfish will complain about the imixs-core components. 

Can you please make a test for that. Than we need to discuss the JDK version issue in general.

===
Ralph

**Comment by rsoika** [comment]
I checked it once again. You need to run your project with JDK 8. The reason why we force compiler options to 1.8 is that we depend on the latest version of Lucene (6.2x) which also requires JDK 8.

I hope it is not too cumbersome for you to switch to JDK 8?

Maybe a Docker container makes your situation easier? 
We already provide one for JBoss/Wildfly : https://hub.docker.com/r/imixs/wildfly/

If you like to help me, we can build together one Docker container for glassfish?

**Comment by chrisw14** [comment]
Okay, I understand. Thank you.

I will try it by using a WildFly Server in Eclipse.
