### ISSUE TITLE
Search-Query for several strings in list

### ISSUE THREAD

**Issue by chrisw14** [imixs/imixs-workflow#310]
Hi,
I would like to know how a list of strings is exactly saved that I can search for several strings in a list by lucene.
Example: txtworkflowhistory has several entries in a list, for example:
`[Sat Sep 23 16:46:11 CEST 2017, 200, action, admin]`
At imixs-admin the entry is printed out like this:
`xmlItem : 2017-09-23T16:46:11.339+02:00200actionadmin`

Which search query can I use when
* the number after the date should be greater than 100
* the next item should be a string, e.g. "action" or "finished"
* the last item should be the username of a user

I tried out these search queries but nothing works. Of course, txtworkflowhistory is indexed.

```
(type: "workitem") AND (txtworkflowhistory: (*action, admin*))
(type: "workitem") AND (txtworkflowhistory: (*actionadmin*))
(type: "workitem") AND (txtworkflowhistory: (*action~admin*))
```

The try
`(type: "workitem") AND (txtworkflowhistory: (*action admin*))`
isn't the solution because then it's looking the whole list for these two strings I think?!

What is the right search query for this example?

Thank you!

**Comment by rsoika** [comment]
Hi Chris,
your will find more information about the search api here:
- http://www.imixs.org/doc/engine/luceneservice.html
- http://www.imixs.org/doc/engine/queries.html

Most important is the 'lucene index configuration' (see imixs.properties). Only if a attribute is listed in prperties '_lucence.indexFieldListNoAnalyze_' or '_lucence.indexFieldListAnalyze_' the attribute will be indexed as a separate field. Only in this case you can use the query syntax:

    FIELDNAME:SEARCH_VALUE

The attribute 'lucence.fulltextFieldList' is used to add field values to the default fulltext-block. But this block can not be searched by field name - only by value.

But, in case of 'txtworkflowhistory' also the _indexFieldListNoAnalyze_ will not work, because this attribute holds a embedded list. It is not possible to search the values of such an item.

I am not sure what you try to achieve with your query, but maybe the fields '$processid' and 'namowner' are sufficient?

The other solution is, that your application adds the missing information into custom fields and you add these custom fields to the '_lucence.indexFieldListNoAnalyze_'

**Comment by chrisw14** [comment]
> But, in case of 'txtworkflowhistory' also the indexFieldListNoAnalyze will not work, because this attribute holds a embedded list. It is not possible to search the values of such an item.

This is what I want to do. If it's not possible I have to add the List.toString() output to an extra field.
I would like to filter on users who were participated to a workitem...

**Comment by rsoika** [comment]
yes - we discussed this several times in the past if it wouldn't be a good solution to add a new standard field listing all participants. 
e.g. $AllParticipants

**Comment by chrisw14** [comment]
Because of your sentence:
> It is not possible to search the values of such an item.
It's possible to search the value of a item of the list. But not a specific field in the list or more fields of the list... But I think this entry of imixs-admin is the indexed string:

>  At imixs-admin the entry is printed out like this:
> `xmlItem : 2017-09-23T16:46:11.339+02:00200actionadmin`

There the string has no delimeter but this search query won't work too:

> `(type: "workitem") AND (txtworkflowhistory: (*actionadmin*))`

Strange thing..

**Comment by chrisw14** [comment]
Hi Ralph,

> It is not possible to search the values of such an item.

I tried it out and found at that it's possible to search a single value of a item but not multiple in multiple items. But in the imixs-admin the value
`xmlItem : 2017-09-23T16:46:11.339+02:00200actionadmin`
is shown. Where is this value from? Is this the lucence query? Would the query "*actionadmin*" find it?

Does #312 fix this issue? In my example it doesn't work :-(

**Comment by rsoika** [comment]
Hi Cris, issue #312 has nothing to do with your problem.

What you need is to simply define one or two new fields in your application. E.g. '_Participants' where you add the current editor or whatever you want to search for. This can be best done by a plugin. Next you add these fields into the property _indexFieldListNoAnalyze_. So you will be able to query this fields with lucene - also with multi-values.
The field 'txtworkflowhistory' is a combination out of timestamp, userid and comment. It is not possible for lucene to combine such data in a query. Don't be distracted by the content of this field being displayed as a string. This is the result of the ToString () method.

**Comment by rsoika** [comment]
Once again, you say you want to query:

- the number greater than 100 (I guess the $processID)
- a string, e.g. "action" or "finished" (I guess the event - $activityID)
- the username of a user ($editor)

This can be done with a lucene query like this:

`($processid:[100 TO 9999]) ($event:20) ($editor:"admin")`

But I guess you want to find any workitem where the 'admin' fired the event 20 in a Task >= 100.

Now you have a problem, because this it something which maybe happened some time in the process flow of a workitem where the $processID and $editor has changed.  

Even if you use Wildcard Queries I think this will not work. 

You must more think on the level of Business Process Management.
Again I guess that you want to find the managers in a company who have approved a task?
To solve this you need to define a custom field holding this information.
E.g. '_taskApprovedByManager' where you put in the manager in the corresponding event. 

The RulePlugin can do this for your:

```
var result={}; 
result._taskapprovedbymanager=workitem.$editor[0];
```
And of course you can do the same with the point of time when the task was approved to query the date. If the RulePlugin can not fix it, write your own plugin to compute this application specific processing information.   

But with the standard data Imixs-Workflow is generating, lucene is not able to query such information.

**Comment by chrisw14** [comment]
Thank you Ralph for these informations.
Of course I can implement it by myself by saving the toString of the list in an extra field. I think it's not that good that the same things are saved twice but it's no problem for me.
I only thought you are working on it because the other issue sounds very simular to my question ;-)
