### ISSUE TITLE
No case-sensitive user principal

### ISSUE THREAD

**Issue by chrisw14** [imixs/imixs-workflow#540]
I found out that I can login with "admin" and "Admin", so the login of the username is not case sensitive. 
In my application,  the userprofile of the user can't be found if the username is not exactly the same. 
Is it possible that methods like LoginController.getUserPrincipal() or WorkflowService.getUserName() returns the username in lowercase letters that the username is always the same?
Or is there another solution for this problem?

Thank you

**Comment by rsoika** [comment]
I know this issue but it has nothing to do with the Imixs-Workflow system in general. It is a question of the security/login module you are using. If you have a login-form you can lowercase the user input immediately before he submit the form. 
In Imixs-Marty we have [here](https://www.imixs.org/marty/concepts/security.html) some information how to deal with this issue. 
LoginController or WorkflowService is not the right place. Its to late there because these methods use the 'callerPrincipal' which is the only truth.

**Comment by rsoika** [comment]
Which login module are you using?

**Comment by chrisw14** [comment]
I'm using "j_security_check". Therefore I have no possibility to change anything, as far as I know.

**Comment by rsoika** [comment]
I guess you have a login form. So just lowercase the user input there.

**Comment by chrisw14** [comment]
Yes, but I have no backend because I'm using only "j_security_check" as action address of the form.
Only possibility would be to use JavaScript to lowercase the input...

**Comment by rsoika** [comment]
yes - you need to use javascript here

**Comment by chrisw14** [comment]
Okay
