### ISSUE TITLE
Does IMIXS have a web－based modeler？

### ISSUE THREAD

**Issue by RuiBaiXYZ** [imixs/imixs-workflow#573]
**Does IMIXS have a web－based modeler，or have a plan？**

**Comment by rsoika** [comment]
no, we do not have a web based modeler.
The reason is that we believe that for a technical modeling you need much more features as can be provided by an web interface. 
For example:
 - version control (for developer teams - e.g. Git)
 - version text compare
 - version history
 - the possibility to write junit tests for your models

For that reasons there is also no plan to implement one.

Do you have an example of a web based modeler for BPMN which is open source?

**Comment by RuiBaiXYZ** [comment]
Thanks for your reply.
